// <auto-generated />
using EduApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduApi.Data.Migrations
{
    [DbContext(typeof(EduContext))]
    [Migration("20251011182809_RemoveKey")]
    partial class RemoveKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EduApi.Data.Models.ScoreResponse", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Credit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gpa")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeDetail")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModelUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UserModelUsername");

                    b.ToTable("scores");
                });

            modelBuilder.Entity("EduApi.Data.Models.UserModel", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreResponsesUpdateTime")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("EduApi.Data.Models.ScoreResponse", b =>
                {
                    b.HasOne("EduApi.Data.Models.UserModel", null)
                        .WithMany("ScoreResponses")
                        .HasForeignKey("UserModelUsername");
                });

            modelBuilder.Entity("EduApi.Data.Models.UserModel", b =>
                {
                    b.Navigation("ScoreResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
